import fs from 'fs/promises';
import { exec } from 'node:child_process';
import { getAll } from './service';

const TARGET_FILE = `${__dirname}/cached.ts`;

async function cache() {
  const bundles = await getAll();

  const content = `
// This file is generated by cache.ts
// Do not modify this file directly
import { getAll } from './service';

export const cached = ${JSON.stringify(bundles)} as Awaited<ReturnType<typeof getAll>> // assert enum (Flagship);
 `.trim();

  await fs.writeFile(TARGET_FILE, content, { encoding: 'utf-8' });
  exec(`prettier --write ${TARGET_FILE}`);
}

cache();
